### ISSUE TITLE
New Icon

### ISSUE THREAD

**Issue by ninjagoat** [arminha/worldclockwidget#54]
I made an icon for your app. Would you like to use it?

![wc](https://cloud.githubusercontent.com/assets/8400485/5332119/70233a54-7e6f-11e4-8631-d891a076e045.png)

**Comment by arjerine** [comment]
Sorry I was very busy. Could you please upgrade the gradle version? I'm not able to clone this on Studio

**Comment by arminha** [comment]
I was also quite busy. Will be able to do that Monday evening.

**Comment by arminha** [comment]
Upgraded Gradle and the Android plugin 9867ef1f6066c399414e043d49dd0800932d607d

**Comment by arjerine** [comment]
Could you please add a light theme? :p
