### ISSUE TITLE
populate timeZoneId,city,country,timeDiff from latitude and longtitude values

### ISSUE THREAD

**Issue by dasbiswajit** [arminha/worldclockwidget#75]
Hello @arminha,
I am trying to populate timeZoneId,city,country,timeDiff from latitude and longtitude values. Something like below values -
https://github.com/arminha/worldclockwidget/blob/6a7c4b84a1f44971d333ef2d0d720126a12eb7e3/worldclockwidget/src/main/java/ch/corten/aha/worldclock/WorldClockActivity.java#L331
Any idea how to hack and insert into clocks. I can populate some like city and country from Geocoder library -
Geocoder geocoder = new Geocoder(getActivity(), Locale.getDefault());
                        List<Address> addresses = geocoder.getFromLocation(latitude, longitude, 1);
                        String cityName = addresses.get(0).getLocality();
                        String stateName = addresses.get(0).getCountryCode();
                        String countryName = addresses.get(0).getCountryName();

But unable to populate - timeZoneId, timeDiff any way. Any help will be appriciated.

Regards
Biswajit

**Comment by arminha** [comment]
Hi @dasbiswajit,

The difficult part is to get the `timeZoneId`. Once you have that it's easy to compute the `timeDiff`like this: 

https://github.com/arminha/worldclockwidget/blob/6a7c4b84a1f44971d333ef2d0d720126a12eb7e3/worldclockwidget/src/main/java/ch/corten/aha/worldclock/AddClockActivity.java#L194

The `timeDiff`is just the current offset to UTC in minutes.

[This Stackoverflow answer](https://stackoverflow.com/a/16086964) has a good overview of how to get the time zone id for a location.
I think we have 3 options:
1. use a web service from the list on Stackoverflow
2. use the offline Java implementation from https://github.com/drtimcooper/LatLongToTimezone
3. use the time zone boundaries from https://github.com/evansiroky/timezone-boundary-builder and create our own offline Java implementation

Option 2 seems to me the most reasonable one for me. A web service comes with additional complexity and quotas, access keys etc to manage,

**Comment by dasbiswajit** [comment]
Option 2 worked. Thanks!!
