### ISSUE TITLE
convert ui to Material design

### ISSUE THREAD

**Issue by dasbiswajit** [arminha/worldclockwidget#78]
Hello @arminha,
Any idea how to get rid of actionbarsharlock to closest match library appcompat?

I am struggling to make it.
following the [link ](https://itaffinity.wordpress.com/2015/07/01/modernizing-android-uis-part-1-migrating-from-actionbarsherlock-to-material-design/)but ended up with lots of error.
Any help appriciated.
Cheers 
Biswajit

**Comment by arminha** [comment]
I started an unfinished appcompat branch three years ago. It's old, so you probably can't use the code directly. But it should show most of the steps.
If I remember correctly, I didn't convert the settings screen and some other widgets.

**Comment by dasbiswajit** [comment]
Implement .
