### ISSUE TITLE
Option to not display seconds

### ISSUE THREAD

**Issue by B00ze64** [arminha/worldclockwidget#84]
Good day. Small change, but I find it distracting to see 10 times the seconds counting-up for 10 cities. Seconds are the same for all cities, I don't really need to see them. Thank you.

**Comment by dasbiswajit** [comment]
Can you please update to latest. This has been fixed already.

**Comment by B00ze64** [comment]
@dasbiswajit I have the latest, 1.8.15, and the seconds are showing, and I do not see an option to hide them...

![image](https://user-images.githubusercontent.com/15389810/46984421-25ff1e80-d0b3-11e8-9aae-94090e723dcd.png)

**Comment by dasbiswajit** [comment]
Chage the date time 24 hrs format to 12 hrs format. It will work. Please sent this support related issues to 
widgetworldclock@gmail.com. this helps for support tge app. Not as issues.

**Comment by dasbiswajit** [comment]
Sure as of now this is not supported. May be check un the future.
